Implementa o trabalho 1.8
Cardoz-0/SurRender pull request #5
Opened 2022-06-15 23:24 UTC by andrefpf

Recomendo testar bastante as rotações, especialmente da window. 

Se der um botão direito nos menus dá pra hablitar um "menu de ferramentas" meio experimental pra usar a ferramenta Pan e girar a tela com o mouse.

2022-06-17 01:39 UTC, gabsilvcar requested changes

2022-06-17 01:39 UTC, nathscrds commented on surrender/main_window.py
> +
remover espaçamento desnecessário

2022-06-17 01:39 UTC, nathscrds commented on surrender/main_window.py
> +
espaçamento

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/main_window.py
> +        self.centralWidget = self.viewport
se ambos atributos de classe são iguais, remover um deles

2022-06-17 01:39 UTC, nathscrds commented on surrender/menus/modify_object.py
> +            self.around_y_line.setPlaceholderText('')
adicionar newline em final de arquivo

2022-06-17 01:39 UTC, nathscrds commented on surrender/shapes/__init__.py
> +from .object_3d import Object3D
adicionar newline no final do arquivo

2022-06-17 01:39 UTC, nathscrds commented on surrender/shapes/cube.py
> +
remover espaço extra

2022-06-17 01:39 UTC, nathscrds commented on surrender/shapes/object_3d.py
> +            yield Line('', a, b, self.color)
adicionar newline no fim do arquivo

2022-06-17 01:39 UTC, nathscrds commented on surrender/tools/__init__.py
> +from .camera_pan_tool import CameraPanTool
adicionar newline no fim do arquivo

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/tools/camera_pan_tool.py
> +
espaço desnecessario

2022-06-17 01:39 UTC, nathscrds commented on surrender/tools/hand_tool.py
espaço desnecessario

2022-06-17 01:39 UTC, nathscrds commented on surrender/vector.py
> +def vector_angle(v0, v1):
todas as funções de vetor devem fazer parte da classe vetor

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/vector.py
> +def vector_x_angle(v):
idem acima

2022-06-17 01:39 UTC, nathscrds commented on surrender/vector.py
> +def vector_y_angle(v):
idem acima

2022-06-17 01:39 UTC, nathscrds commented on surrender/vector.py
> +def vector_z_angle(v):
idem acima

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/vector.py
> +def cross_product(v0, v1):
idem acima

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/vector.py
> +def dot_product(v0, v1):
idem acima

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/viewport.py
> +            print('Não sei desenhar', shape)
Remover print

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/viewport.py
> +    def rotate(self, x, y, z):
x, y, z não poderiam ser um vetor?

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/menus/tools_menu.py
remover espaço

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/projection.py
remover espaço

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/scene.py
remover espaço

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/math_transforms.py
newline duplo ao invez de único após declaração de imports

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/menus/add_object.py
> +
newline duplo

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/shapes/generic_shape.py
> +        return self
retorno não condiz com nome da função

2022-06-17 01:39 UTC, gabsilvcar commented on surrender/vector.py
remover espaço extra

2022-06-18 19:02 UTC, andrefpf commented on surrender/shapes/cube.py
> +
O guia de estilo do python sugere que classes sejam envoltas com duas linhas em branco

https://peps.python.org/pep-0008/#blank-lines

2022-06-18 19:06 UTC, andrefpf commented on surrender/viewport.py
> +            print('Não sei desenhar', shape)
Acha melhor substituir por uma mensagem de erro decente ou ignorar o input?

2022-06-19 19:23 UTC, merged